version: "3.8"

services:
  nodeapp:
    image: node:20-alpine
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npm test
    environment:
      - NODE_ENV=development
    ports:
      - "3333:3000"
